### ISSUE TITLE
cannot read file system information for '%m': No such file or directory

### ISSUE THREAD

**Issue by MacFlurry** [mavam/dotfiles#10]
Yeah, I saw it, but since it's a bit off-topic I quickly swapped it out again. :)

Adding `public_ip_joined` (and also `public_ip`) works for me, by the way:

<img width="338" alt="Screen Shot 2019-08-08 at 12 40 05" src="https://user-images.githubusercontent.com/53797/62696961-e60a7e80-b9d9-11e9-8f58-c67b6b4cce0a.png">

_Originally posted by @mavam in https://github.com/mavam/dotfiles/issues/8#issuecomment-519466744_

-------------------------

Hello,

I just added 
```
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time virtualenv 
                                    vcs background_jobs_joined
                                    time_joined user_joined os_icon_joined 
                                    host_joined public_ip_joined public_ip)
```

and `source .dotfiles/zsh/.zshrc` ( I can see the public IP , but , restarting iterm shows this error)
I got error:
```
stat: cannot read file system information for '%m': No such file or directory
prompt_public_ip:15: bad math expression: operand expected at `"/tmp/p9k_...'
```
I cannot figureout why :-D

**Comment by mavam** [comment]
Have look over here: https://github.com/aluxian/fish-kube-prompt/issues/1. It looks like you are dealing with the wrong version of `stat`.

**Comment by MacFlurry** [comment]
Hello, 

I figured it out. The issue is with gnubin stat. I switched to MacOS stat (bsd) and it works.
I will report it to HomeBrew.

thanks a lot dude :-) 

Did you consider switching to PowerLevel10K? Seems to be 10x faster than the 9K.

Best regards,

Mac

**Comment by mavam** [comment]
> Did you consider switching to PowerLevel10K? Seems to be 10x faster than the 9K.

Great idea. I've switched to it.

**Comment by MacFlurry** [comment]
:D could you upgrade with another branch so I can grab it ? pls pls pls 😁

**Comment by mavam** [comment]
You can just pull from master (or rebase onto master in your topic branch)
