### ISSUE TITLE
How to remove the logo of the clock at the end of time

### ISSUE THREAD

**Issue by wowguoqing** [mavam/dotfiles#13]
[https://github.com/l5211314o/ssm-1/blob/l5211314o-patch-1/Screen%20Shot%202020-04-21%20at%205.19.42%20PM.png](url)

**Comment by mavam** [comment]
That's a good question. The culprit is this line:

```sh
POWERLEVEL9K_TIME_FORMAT="%D{\uf073 %b %d \uf017 %H:%M}" #  Jun 15  09:32
```

This used to work fine. But it no longer works. Maybe you can figure out a fix?!

**Comment by wowguoqing** [comment]
add POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=   ,it works ,but other icons are hide

**Comment by wowguoqing** [comment]
not add POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
only add POWERLEVEL9K_TIME_ICON=  ,it words perfect
