### ISSUE TITLE
googlecode.iterm2.plist

### ISSUE THREAD

**Issue by MacFlurry** [mavam/dotfiles#7]
hello, 

can you please add googlecode.iterm2.plist file on gitignore ? since the last update the googlecode.iterm2.plist changed.

Best regards

**Comment by mavam** [comment]
As of 1b7c7ea462bef6e6c3b0e5f489de292033c3edb2, I intentionally switch the default theme to light. That is, <kbd>COMMAND</kbd> + <kbd>n</kbd> now starts a new window with the solarized light theme, and <kbd>COMMAND</kbd> + <kbd>OPTION</kbd> + <kbd>n</kbd> a dark theme.

Did the recent change cause a conflict on your end?

**Comment by MacFlurry** [comment]
Not conflicting but trying to git pull throws a change in this plist that need to be pushed on origin first.

**Comment by mavam** [comment]
Sorry, but I'm not quite understanding how adding the file to the .gitignore would solve the issue. If you have local changes, then shouldn't a `git pull` go through just fine? Maybe you could elaborate a bit?

**Comment by MacFlurry** [comment]
yeah, you're right , ignore is not the solution :-)

And you're right I can just pull.

thanks dude and sorry for disturbing you :-)

**Comment by mavam** [comment]
No worries, glad we could resolve it. 😄
